### ISSUE TITLE
How do I install torch and other libs in my submission?

### ISSUE THREAD

**Issue by laituan245** [YerevaNN/biorelex-codalab-submission#1]
I have built a code submission similar to yours. However, my code does need to use PyTorch. But I am not sure how to do that in CodaLab environment. Could you give more info on how to modify the metadata file to install torch and other libs before running the program?

Thank you

**Comment by mahnerak** [comment]
@laituan245 I'll post my answer to [codelab forum thread](https://competitions.codalab.org/forums/17190/4643/) you opened.

**Comment by laituan245** [comment]
My issue has been resolved. I am closing this now. Thanks for your help.
